### ISSUE TITLE
Retrievals are Incentivized

### ISSUE THREAD

**Issue by willscott** [filecoin-shipyard/retrieval-incentives#1]
Description: It is profitable (incentivized) and incentive aligned to provide high-quality retrievals from filecoin

ETA: 2024-12-31
Maintainer: @willscott

```[tasklist]
### Milestones
- [ ] On-chain Retrieval SLAs
- [ ] Tracking of observable SP bandwidth
- [ ] Reputation on Chain
- [ ] Contract made for releasing retrieval bounty when SLA met
- [ ] User / demonstration of contract effectiveness
```
